# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/freq-beat',
                'doc_host': 'https://Spstolar.github.io',
                'git_url': 'https://github.com/Spstolar/freq-beat',
                'lib_path': 'freq_beat'},
  'syms': {'freq_beat.core': {'freq_beat.core.foo': ('core.html#foo', 'freq_beat/core.py')}}}