# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_combiner.ipynb.

# %% auto 0
__all__ = ['transfer_notes_from_beat']

# %% ../nbs/01_combiner.ipynb 3
import os
from pathlib import Path
from random import choices, random
import pretty_midi

def transfer_notes_from_beat(beat_notes, target, offset):
    for note in beat_notes:
        start = note.start + offset
        end = note.end + offset
        translated_note = pretty_midi.Note(start=start, end=end, velocity=note.velocity, pitch=note.pitch)
        target.notes.append(translated_note)
