# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_beatmanager.ipynb.

# %% auto 0
__all__ = ['store_beat']

# %% ../nbs/00_beatmanager.ipynb 3
import os

def store_beat(beat, beat_name):
    if not os.path.exists("beats"):
        os.mkdir('beats')
    filename = f"beats/{beat_name}.mid"
    print(f"Writing beat to {filename}.")
    beat.write(filename)
