# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_notesplitter.ipynb.

# %% auto 0
__all__ = ['copy_note', 'split_note']

# %% ../nbs/03_notesplitter.ipynb 3
from pretty_midi import Note

def copy_note(note: Note, start=None, end=None, velocity=None, pitch=None):
    if start is None:
        start = note.start
    if end is None:
        end = note.end
    if velocity is None:
        velocity = note.velocity
    if pitch is None:
        pitch = note.pitch
    
    return Note(start=start, end=end, velocity=velocity, pitch=pitch)
    
def split_note(note: Note, num_pieces):
    start = note.start
    pitch = note.pitch
    velocity = note.velocity
    note_length = note.end - note.start
    piece_length = note_length / num_pieces
    start_times = map(lambda x: start + x * piece_length, range(num_pieces))
    return [copy_note(note, start=piece_start, end=piece_start + piece_length) for piece_start in start_times]
